spring:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format-sql: true

  config:
    import: optional:secrets.yml

  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL
    username: root
    password:
    driver-class-name: org.h2.Driver
