spring:
  config:
    import: optional:secrets.yml

  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL
    username: root
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
